apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ulpf
  namespace: ulpf
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ulpf.example.com
      secretName: ulpf-tls
  rules:
    - host: ulpf.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ulpf
                port:
                  name: http