"""Models for AI-generated parser proposals."""

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class ParserProposal(BaseModel):
    """
    Structured proposal for a parser generated by the local AI factory.

    This model represents a suggestion only.
    It does not execute, activate, or register a parser.
    """

    parser_name: str = Field(
        ...,
        description="Proposed unique parser name",
    )

    vendor: Optional[str] = Field(
        default=None,
        description="Detected or inferred vendor name",
    )

    product: Optional[str] = Field(
        default=None,
        description="Detected or inferred product name",
    )

    format_type: str = Field(
        ...,
        description="Detected log format such as json, key_value, or plain_text",
    )

    mappings: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping from source/vendor fields to canonical fields",
    )

    timestamp_field: Optional[str] = Field(
        default=None,
        description="Source field containing the event timestamp",
    )

    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence in the proposed parser",
    )

    reasoning: List[str] = Field(
        default_factory=list,
        description="Evidence or reasoning behind the proposal",
    )

    source: str = Field(
        default="local_ai",
        description="Origin of the proposal",
    )